---
- name: This is a declarative format
  hosts: dev
  become: yes
  tasks:
    - copy: 
        src: /etc/passwd
        dest: /tmp
    
    - file:
        path: /tmp/aws
        state: directory

    - yum:
        name: git
        state: present
        update_cache: yes
        