---
- name: Intalling apache2 ONLY on Ubuntu 18.04
  hosts: Ubuntu
  become: yes
  tasks:
    - name: Installing apache2
      apt: 
        name: apache2
        state: present   
      when: ansible_distribution_major_version == '18' and ansible_os_family == 'CentOS'