AWSTemplateFormatVersion: 2010-09-09
Description: Creating a EC2 Instance
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0ad21ae1d0696ad58
      InstanceType: t2.micro
      KeyName: keypair3
      BlockDeviceMappings:
        - DeviceName: /dev/sdm
          Ebs:
            VolumeType: io1
            Iops: 200
            DeleteOnTermination: false
            VolumeSize: 10