AWSTemplateFormatVersion: 2010-09-09
Description: A sample template
Parameters:
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.  
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0ad21ae1d0696ad58
      InstanceType: !Ref InstanceTypeParameter    
      KeyName: !Ref KeyName
      BlockDeviceMappings:
        - DeviceName: /dev/sdm
          Ebs:
            VolumeType: io1
            Iops: 200
            DeleteOnTermination: false
            VolumeSize: 10
#  MyEIP:
    #Type: 'AWS::EC2::EIP'
#    Properties:
#      InstanceId: !Ref MyEC2Instance