---
- name: Usuage of variables
  hosts: all
  become: yes
  vars_files:
    - /Variables/variables.yml

  tasks:
    - name: Intalling 3 packages using variables
      apt:  
        name: "{{ package_name }}"
        update_cache: yes
        state: present