---
- name: Usuage of variables
  hosts: all
  become: yes
  vars:
    dirname: /tmp/ansible2
    filename: /etc/passwd

  tasks:
    - file:
        path: "{{ dirname }}"
        state: directory
    
    - copy:
        src: "{{ filename }}"
        dest: "{{ dirname }}"